### ISSUE TITLE
Trocar lógica do btn generate das para lógica Tab e Enter

### ISSUE THREAD

**Issue by daniel-francelino** [daniel-soaress/automation_python#11]

**Comment by daniel-francelino** [comment]
Branch: feat/11

**Comment by Isaacvf-dev** [comment]
Devido a dificuldade na contagem do número de tabs para selecionar outros meses, sem ser o mês anterior. Foi sugerido manter a lógica de click pela imagem para clicar em gerar das

**Comment by Isaacvf-dev** [comment]
Também foi necessário inserir o comando `pyautogui.press('pgdn')` para descer a tela e garantir que encontre o botão apurar/ gerar DAS. Contudo, também foi adicionado a linha de código `pyautogui.sleep(1)` pois não estava sendo reconhecido a imagem logo após a descida da barra de rolagem.
