### ISSUE TITLE
Migrar funções

### ISSUE THREAD

**Issue by daniel-francelino** [daniel-soaress/automation_python#24]
- [x] Necessário criar o diretório "helpers" onde criará o arquivo python "utils";
- [x] As seguintes funções "close_tab()", "loading_screen", "getCnpj", "getAuto", "getMonth", "getYear" devem ser exportadas no arquivo "utils".
- [x]  Então no script "generate_das.py" devem ser importadas para utilização;
- [x]  O arquivo "config.txt" deve ser alterado o nome para "env.txt" e movido para o diretório principal;
- [x]  as funções que realizam leitura de arquivo, devem ser alteradas e localizar o arquivo "env.txt"

**Comment by Isaacvf-dev** [comment]
Não seria melhor deixar o arquivo env.txt em uma pasta chamada config? Em vez de deixar no diretório principal
